language: python
python: 2.7
sudo: required
dist: trusty
script: echo done
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: Ruairi.Fahy
  password:
    secure: "cDnxavm6ZlGmDr6TfcV2vO82JwTu8iBeeawrbY7b4YseVCuOHyXXrfaVRV+P2km8C0swFBpEY6atQJvRSzmqSx25P1JIxdJW8Mkoq/UIvapFfqzipFZM+soqgkNQPQl2RXb3Dcj0rp0889QjzfBveQMVFt3AHijsYTRQPvMdJwbrIPYegxuG8pUh2rzFkSAk2L34D9LuITIXCEN0NQDgPdCqKnUlg+B62Hcsh8yY6TcATTdESH5gZBtL7jmqienGzsn9gctpNaCXiP8jzHPkpb3PuEXqiB/CkmcliuFfvPguCMK2ytCP0/ScKv4gVSuhFwx+1wMuk8w/9E9xEfbX/aa7r+39NbREAe/21X/nPnKyymrV4PKjxzEGDODIG4hZMysgIdINydRJcl3rKRTMJ5fuC6j2/KRmroQBPRhTWZn6m/UCs/iGi1x6BPlJ3xh7b/3WSmFN8vjAnesFhFa6cMCrxh/MH7DY8t2ChP1UGuCaYoc7N69shseeVxsI3r37UJ5S2ZtlbPpmvypB8dBJv9R4srMwm1ugBvju5Dev0NhJSoxIB7o9wcDofp1xwlo25oXnOAMZQkTm5V8WNV43QoRTCJlGITVNfLZ0aMrK+rkQhDJDj4+87EB+3kxuqe04ocr25kHNfBjzjU79DsGcbkwe5Wl2IhKsavZqsw6j0sE="
  on:
    all_branches: true
    tags: true
    repo: scrapinghub/portia2code
    condition: $TRAVIS_TAG =~ ^portia2code-[0-9][.][0-9]*
